@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam classFontSize 18
skinparam classFontName Menlo
skinparam classAttributeFontSize 18
skinparam classAttributeFontName Menlo
skinparam shadowing false
skinparam arrowFontSize 18
skinparam arrowFontName Menlo

hide circle

class Club {
+join(member: Member) : void
+join(Leader: leader) : void
}

Club "1 " *-- "1" Member : "   "
Club "1" *-- "1 " Leader : "   "
@enduml