@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam classFontSize 18
skinparam classFontName Menlo
skinparam classAttributeFontSize 18
skinparam classAttributeFontName Menlo
skinparam shadowing false

hide circle

class ClassA {

}

class ClassB extends ClassA {

}

interface ClassC {

}

class ClassD implements ClassC {

}

class ClassD {

}

class ClassE {

}
@enduml