@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam classFontSize 18
skinparam classFontName Menlo
skinparam classAttributeFontSize 18
skinparam classAttributeFontName Menlo
skinparam shadowing false

hide circle

interface Player {
+poll(player : Player) : void
}

class Villager implements Player {
-name : String
#vote : int
+Villager(name : String)
+poll(player : Player) : void
}
@enduml