@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam classFontSize 18
skinparam classFontName Menlo
skinparam classAttributeFontSize 18
skinparam classAttributeFontName Menlo
skinparam shadowing false

hide circle

interface Player {
[ 3 ] poll(player : Player) : void
}

class Villager implements Player {
[ 4 ] name : String
[ 5 ] vote : int
[ 6 ] Villager(name : String)
[ 7 ] poll(player : Player) : void
}
@enduml